#! /usr/bin/make -f

ASMFILES = a0.out a1.out a2.out a3.out a4.out a5.out a6.out a7.out a8.out a9.out aa.out ab.out ac.out ad.out ae.out af.out ag.out ah.out ai.out aj.out ak.out al.out am.out ao.out aq.out at.out aw.out ax.out az.out y.out gamma.out globals.out ecvt.out 

include ../common.mak
